### ISSUE TITLE
Bin values <= 0 treated as transparent

### ISSUE THREAD

**Issue by robharper** [unchartedsoftware/aperture-tiles#113]
[This line](https://github.com/oculusinfo/aperture-tiles/blob/develop/tile-service/src/main/java/com/oculusinfo/tile/rendering/impl/DoublesImageRenderer.java#L179) assumes that data stored in the tile is always a record count and that only > 0 values are valid and renderable:

``` java
if (binCount > 0) {
  // render
} else {
  // transparent
}
```

If the bin values are a function of actual data values negative and zero values may be valid data. As such transparent should only be used when the tile reports "no data" for a bin.

There is one gotcha, however. With this chage if plotting data counts, a count of zero would render the lowest color in the spectrum (say dark blue) and would be visually wrong (e.g. it would obscure the map). A count of zero needs to look like the absence of data for this change to work.

**Comment by cdbethune** [comment]
Before we can adjust the rendering side of this, we need to ensure there is proper support for dealing with NO_DATA values in the tiles themselves.  Currently if you build a heatmap of tiles it will set the initial value for all heatmap elements to zero, rather than some pre-defined NO_DATA value.  We should be able to set NO_DATA for the various analytics as supplied as an optional parameter with an appropriate default, and that value should be applied to all bins initially.
